// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_YHSEEqCKGGHKd2p2R23Ps4CeTvwK2zU',
    appId: '1:698141561736:web:aa422703dcfccaed75603d',
    messagingSenderId: '698141561736',
    projectId: 'tote-839d8',
    authDomain: 'tote-839d8.firebaseapp.com',
    databaseURL: 'https://tote-839d8-default-rtdb.firebaseio.com',
    storageBucket: 'tote-839d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe38m22QA-lqEEbsxC9pQaraUGtmX1Sos',
    appId: '1:698141561736:android:b08d08262762d69b75603d',
    messagingSenderId: '698141561736',
    projectId: 'tote-839d8',
    databaseURL: 'https://tote-839d8-default-rtdb.firebaseio.com',
    storageBucket: 'tote-839d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCca2le5AAhcrQkYGUwss-rByVy5ysmgYI',
    appId: '1:698141561736:ios:44b647846e0815b275603d',
    messagingSenderId: '698141561736',
    projectId: 'tote-839d8',
    databaseURL: 'https://tote-839d8-default-rtdb.firebaseio.com',
    storageBucket: 'tote-839d8.firebasestorage.app',
    iosClientId: '698141561736-ml517tev8cv6a5ig0mnqdco2kupdcuv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCca2le5AAhcrQkYGUwss-rByVy5ysmgYI',
    appId: '1:698141561736:ios:44b647846e0815b275603d',
    messagingSenderId: '698141561736',
    projectId: 'tote-839d8',
    databaseURL: 'https://tote-839d8-default-rtdb.firebaseio.com',
    storageBucket: 'tote-839d8.firebasestorage.app',
    iosClientId: '698141561736-ml517tev8cv6a5ig0mnqdco2kupdcuv0.apps.googleusercontent.com',
    iosBundleId: 'com.example.toteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_YHSEEqCKGGHKd2p2R23Ps4CeTvwK2zU',
    appId: '1:698141561736:web:7ff2af7f2093473e75603d',
    messagingSenderId: '698141561736',
    projectId: 'tote-839d8',
    authDomain: 'tote-839d8.firebaseapp.com',
    databaseURL: 'https://tote-839d8-default-rtdb.firebaseio.com',
    storageBucket: 'tote-839d8.firebasestorage.app',
  );
}
