services:
    # Backend API service
    - type: web
      name: tote-api
      env: node
      plan: free
      buildCommand: npm install
      startCommand: npm start
      envVars:
          - key: NODE_ENV
            value: production
          - key: PORT
            value: 10000

databases:
    # PostgreSQL Database
    - name: tote-db
      plan: free
      databaseName: tote
      user: tote_admin
